### ISSUE TITLE
The future of RSPET - Roadmap - What's ahead

### ISSUE THREAD

**Issue by panagiks** [panagiks/reverse_shell#45]
Dear contributors, users, geeks and robots,

This will be a quick summary about what I see ahead of us for RSPET. I have planned a couple of things to revamp and push the project forward (mainly to excuse myself for a prolonged period of inactivity).

TODOs:
- [ ] Move the project under the [RSPET](https://github.com/RSPET) Github organization
- [ ] Split the project in two, the server Module and the Client module (This will allow for easier management, updates and also allow for multiple clients to be built, i.e. in different programming languages)
- [ ] Rewrite the server module in an API first principle (this will not in any way deprecate or change the way the command line interaction works; it will just make the API feel less "forced" on the project and more natural)
- [ ] Consider asyncio implementation for the server module
- [ ] Rewrite the client module to be even more bare-bones an migrate optional functionalities to plugins
- [x] Create "Client Profiles" on the server, a way to automatically "equip" a client with the required plugins
- [ ] Write tests .... oh I've been putting it off for quite a while ...
- [ ] Add some CI for testing PRs and releasing rspet_server to pypi
- [ ] Add packaging for both server and client for different OSs
- [ ] Consider an architecture with "swappable" transports (i.e. to allow communication over http(s)). That's gonna be a tricky one 
- [x] Add decent logging
